### ISSUE TITLE
Visual confirmation that an item has been completed?

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#100]
Right now the item should just disappear from your list, but can we make this more obvious through animation?

** RecyclerView should have some default animations to help with this
(probably a goal for a later milestone)

**Comment by ryanmerkley** [comment]
I'm unclear from this issue if it incorporates #83 and #112 or not. If it does, the title should be changed. This item now includes a series of UI improvements:

- uploaded photos should have a progress bar
- app should indicate photo upload confirmation
- app should confirm image capture
- app should manage a list of completed list items
- app should indicate that an item is complete, and has been removed from the list (and give the user an "undo" option to return it to the list (e.g. use case: list maker calls for images of crowd at a concert. user wants to upload many against that item).

This feels like it might be multiple issues, and this bug is getting a big unwieldy.

**Comment by perpetuatingcuriosity** [comment]
I think we accomplished this with the notifications. Closing for now, but it would be good to come back to this for 2.0 when we’ll have more room to do re-designing.
