### ISSUE TITLE
You can add items to your list multiple times

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#122]

**Comment by perpetuatingcuriosity** [comment]
@mattl Can we fix this by checking if items are in a user’s list before sending the 20 random items for **/api/items/**

It’s just really confusing for a user to, for example: delete “chocolate” and then see two more “chocolate” in the list because it was added multiple times. 

(Then when the list refreshes, all the chocolates are gone regardless of whether the 2nd or 3rd entries for “chocolate” were deleted or not.)
