### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by tarkowski** [creativecommons/list#237]
Hello, 
Firstly, I'm new to this :) But excited about the project and happy to share insight as a tester. I'm not sure how bare bone the new version is - but the current version lacks any form of communication about the copyright aspect of the process (save for some "about" information). I read the functional specs and I know that you're aiming for a minimalist design and workflow, but I think that you cannot avoid some more information / checks about copyright status. I think this is a generally interesting issues, what's the proper "copyright UI" - this applies to a lot of projects, including the new "Platform project". I believe that you cannot (unfortunately) make the copyright layer transparent. For example, I've just uploaded to the list a photo of a graffiti - which is somebody's copyrighted work, and I actually don't have any copyright in the photo I can license, as it's a purely technical, documentation photo. But the system will openly license this on my behalf, and ignore the fact that somebody's copyright's are in the image - and as a user I don't receive prompt to think about this.

**Comment by sarahpearson** [comment]
Thanks for the feedback! In the test phase of the app, we're dumping all images we receive. Starting with the next release, we'll be keeping them on our servers, so the app will make it more clear to users that they should only upload original photos. (The new TOS will also reflect that.) 

As far as specific prompts to think about copyright issues before upload, that is something to think about down the road. Like every platform that allows user-generated content, we'll be thinking about how best to inform users of copyright concerns.

**Comment by tarkowski** [comment]
great. it would be cool if we could ourselves set a standard for others, it seems not too many platforms are getting this right. Please don't think of this just as a TOS issue, we need the equivalent of the CC Deed too :)

**Comment by ryanmerkley** [comment]
Alek, these are the right questions to be asking. We need to balance encouraging people to upload images, with bombarding them with so many legal warnings that they're afraid to upload anything. We should think about what are the main things people need to know, in human-readable format, that we want to share immediately, and while using the app. Otherwise we'll just end up with a big disclaimer that no one reads (not what you're suggesting, I know, but a real risk as we look at all the myriad restrictions a user could encounter taking pictures of things, including that the grafitti for example might be permitted to be used in some cases, and some countries, but not others).
