### ISSUE TITLE
“Like” a photo endpoint

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#318]
You should be able to show appreciate by adding a “like” someone else’s photo from the Discover tab. A user’s likes should also be tracked. 

This is a requirement for basic photo feed for 5.0 MVP. #308

**Comment by robmyers** [comment]
@perpetuatingcuriosity if there isn't an example I can use as a model (that was very useful for the photo feed), I suggest:

To like a photo, PUT to

    /api/photo/:photoid/like

To remove an existing like, DELETE to

    /api/photo/:photoid/like

With the following POST values:

**skey** - the current session key

**userid** - the user id for the current session

Note the use of `photo` rather than `photos`, this is to try and make this section of the api more regular. Another alternative would be to use `api/like/photo/:id`. We can use whichever people prefer (or something else entirely :-) ).

Return values:

Where the user is not logged in, 401.

Where the photo id does not exist, 404.

In all other circumstances (including liking a photo the user has already liked, and liking a blocked photo), 200.

Other considerations:

A "likes" field will be added to all photo data returned by the API. This will include a numeric count of likes for the photo, 0 for no likes. Photos blocked by a user should not count towards likes, but this will not be implemented in the first version of this.

Like data will not be accessible separately.

**Comment by perpetuatingcuriosity** [comment]
@robmyers I’ve recently seen a single endpoint used for likes, where it user likes are toggled, e.g.:

Say a user decides to like a photo:

    /api/photo/:photoid/like

the response would be:

```
{
"success": true,
"likes": true
}
```

When the request is received, we would run a check to see the user already likes this photo. Say the user already likes it, we would interpret that as the user trying to “unlike” the photo, so we’d make the change in the db and return: 

```
{
"success": true,
"likes": false
}
```

What do you think? 

The userid, skey POST values + adding a “likes” field to all photos sounds good. :thumbsup:

**Comment by mattl** [comment]
I like this.

Do we care about when they like it? For example... I think if you like a photo, maybe you don't get to unlike it after a period of time has passed... like a few hours.

**Comment by robmyers** [comment]
The example I had in mind was Github's gist starring system:

https://developer.github.com/v3/gists/#star-a-gist

The gist starring system is more RESTful - we have separate actions to add and remove something. 

But the toggle system is simpler, and people can check a photo's like state before setting it either by getting the photo info or if we make logged-in GET return the existing status.

I will therefore implement the toggle system. Thank you .

We should update blocks to use this at some point (and we should move photo blocks to /api/photo/:photoid/block using the same system).

@mattl You should be able to change the like status at any point IMO. Is locking likes after a while intended to make caching this more efficient?

**Comment by mattl** [comment]
I'm thinking we might push those likes out :) Like a photo on The List, and it gets liked elsewhere eventually.

**Comment by robmyers** [comment]
Oh that's a really good idea. I would stand up for a user's right to change their mind in whatever we implement, though. :-)

**Comment by robmyers** [comment]
Implemented as agreed and deployed to Staging. Tested with unit tests (for database access) and curl (for API access). Please see docs/api.md for example.
