### ISSUE TITLE
API /users/login creates a new user every time

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#339]

**Comment by robmyers** [comment]
Please provide sample curl session.

**Comment by mattl** [comment]
The example in api.md ;)

**Comment by robmyers** [comment]
For calls of the following form:

    curl --include --data "$DATA" https://thelist.creativecommons.org/api/users/login

with the following parameters as $DATA, here are the results.

    username=&password=

or

    ""

Gives new skey, userid and GUID email each time when called repeatedly.

    username=[previous GUID]

or

     username=[previous GUID]&password=

Gives the same skey, userid and email as the previous call that generated the GUID and returned it as the "email" field when called repeatedly.

    username=[valid CCID]&password=[valid CCID password]

Gives the same skey, userid and email when called repeatedly.

    username=[valid CCID]&password=[incorrect CCID password]

or

    username=[valid CCID]&password=

Gives a 401 Unauthorized HTTP return code.

The only values that give a new userid each time are the empty username and password. Is this expected behaviour?

**Comment by mattl** [comment]
Seems okay, I may have made a mistake previously.
