### ISSUE TITLE
Can't see your photos immediately when the upload works

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/list#88]
Kind of a bummer that you can't see your image right away when the upload works. Have to wait and go into "My images" to see it. I imagine that is a technical issue, but it would be nice to see it right away.

**Comment by mattl** [comment]
Images need to be processed and uploaded to The Internet Archive.

**Comment by ryanmerkley** [comment]
This isn't an IA issue, it's a UI issue. There's very little feedback to the user on upload. No progress bar, no confirmed upload, and it doesn't take me to "my uploaded images" gallery or otherwise. Regardless of the upload, it could show something - a thumbnail that says "you will be notified when the image is in the Archive".

**Comment by mattl** [comment]
@ryanmerkley can you make a new issue for that? (Tagged against the android app and feature enhancement) I agree we need some more feedback to the user, but that's not what this issue is about.
